# NumPy 기초

## 넘파이 임포트

In [1]:
import numpy as np

## 파이썬 리스트

In [2]:
data = [1, 2, 3, 4]
result = []

for i in data:
    result.append(i * 10)
result

[10, 20, 30, 40]

## ndarray

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr10 = arr * 10
arr10

array([10, 20, 30, 40])

## 2차원 데이터

데이터를 행 단위로 구성하는 경우 열 단위로 인덱싱할 수 없습니다. 

In [4]:
price = [
    [100, 80, 70, 90],
    [120, 110, 100, 110]
]

price[0]

[100, 80, 70, 90]

In [5]:
import numpy as np

arr = np.array(price)
arr

array([[100,  80,  70,  90],
       [120, 110, 100, 110]])

## 넘파이 인덱싱

In [6]:
arr[0]

array([100,  80,  70,  90])

In [7]:
arr[1]

array([120, 110, 100, 110])

In [8]:
arr[0, 0]

100

In [9]:
arr[1, 0]

120

In [11]:
arr[:, 0] # 첫 번째 컬럼

array([100, 120])